name: Django Tests

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7  # Or use latest if needed
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=test_user --password=test_pass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Debug File Path
        run: ls -R
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r simple-django-login-and-register-master/requirements.txt
          python source/manage.py makemigrations
          python source/manage.py migrate
          python source/manage.py runserver
      - name: Print Success Message
        run: echo "Success"

          
          

     
